services:
  app:
    build: .
    # command: ["sh", "/.devcontainer/scripts/start.sh"]
    volumes:
      - ..:/workspaces
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=True
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - WORKSPACE_NAME=${WORKSPACE_NAME}
    command: ["/bin/sh", "-c", "chmod +x /workspaces/$WORKSPACE_NAME/.devcontainer/scripts/start.sh && /workspaces/$WORKSPACE_NAME/.devcontainer/scripts/start.sh"]

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

volumes:
  postgres_data:
